(("axi_if_converter (ent)" . #<marker at 169 in axi_if_converter.vhd>)
 ("RTL (arch)..."
  ("*architecture declaration*" . #<marker at 9815 in axi_if_converter.vhd>)
  ("axi_lite_regs (cmp)" . #<marker at 14269 in axi_if_converter.vhd>)
  ("input_buffer (cmp)" . #<marker at 16776 in axi_if_converter.vhd>)
  ("core_converter (cmp)" . #<marker at 19998 in axi_if_converter.vhd>)
  ("core_converter (cmp)" . #<marker at 24151 in axi_if_converter.vhd>)
  ("axi_lite_master (cmp)" . #<marker at 28305 in axi_if_converter.vhd>)
  ("clk_div (cmp)" . #<marker at 30205 in axi_if_converter.vhd>)
  ("clk_sync (cmp)" . #<marker at 30503 in axi_if_converter.vhd>)
  ("pattern_counter (cmp)" . #<marker at 30771 in axi_if_converter.vhd>)
  ("pattern_counter (cmp)" . #<marker at 31352 in axi_if_converter.vhd>)
  ("core_fsm (cmp)" . #<marker at 31933 in axi_if_converter.vhd>)
  ("core_fsm (cmp)" . #<marker at 32757 in axi_if_converter.vhd>)))
