(("axi_if_converter" . #<marker at 169 in axi_if_converter.vhd>)
 ("RTL"
  ("*architecture_body*" . #<marker at 9815 in axi_if_converter.vhd>)
  ("axi_lite_regs" . #<marker at 14269 in axi_if_converter.vhd>)
  ("input_buffer" . #<marker at 16776 in axi_if_converter.vhd>)
  ("core_converter" . #<marker at 19998 in axi_if_converter.vhd>)
  ("core_converter" . #<marker at 24151 in axi_if_converter.vhd>)
  ("axi_lite_master" . #<marker at 28305 in axi_if_converter.vhd>)
  ("clk_div" . #<marker at 30205 in axi_if_converter.vhd>)
  ("clk_sync" . #<marker at 30503 in axi_if_converter.vhd>)
  ("pattern_counter" . #<marker at 30771 in axi_if_converter.vhd>)
  ("pattern_counter" . #<marker at 31352 in axi_if_converter.vhd>)
  ("core_fsm" . #<marker at 31933 in axi_if_converter.vhd>)
  ("core_fsm" . #<marker at 32757 in axi_if_converter.vhd>)))
