(("global_sim"
  ("*package_declaration*" . #<marker at 205 in global_sim.vhd>)
  ("Procedures"
   ("read_control_reg" . #<marker at 1858 in global_sim.vhd>)
   ("read_status_reg" . #<marker at 1995 in global_sim.vhd>)
   ("read_version_reg" . #<marker at 2132 in global_sim.vhd>)
   ("read_counters" . #<marker at 2269 in global_sim.vhd>)
   ("read_master_lite_rd_data_reg" . #<marker at 2406 in global_sim.vhd>)
   ("write_control_reg" . #<marker at 2557 in global_sim.vhd>)
   ("write_converter_setup_reg" . #<marker at 2746 in global_sim.vhd>)
   ("write_mm2s_size_reg" . #<marker at 2935 in global_sim.vhd>)
   ("write_master_lite_wr_setup_reg" . #<marker at 3124 in global_sim.vhd>)
   ("write_master_lite_wr_add_reg" . #<marker at 3313 in global_sim.vhd>)
   ("write_master_lite_wr_data_reg" . #<marker at 3502 in global_sim.vhd>)
   ("write_master_lite_rd_setup_reg" . #<marker at 3691 in global_sim.vhd>)
   ("write_master_lite_rd_add_reg" . #<marker at 3880 in global_sim.vhd>)
   ("write_control_reg_system_enable" . #<marker at 4095 in global_sim.vhd>)
   ("write_control_reg_system_stop" . #<marker at 4236 in global_sim.vhd>)
   ("write_control_reg_soft_reset" . #<marker at 4377 in global_sim.vhd>)
   ("write_master_lite_write_request" . #<marker at 4518 in global_sim.vhd>)
   ("write_master_lite_read_request" . #<marker at 4759 in global_sim.vhd>)
   ("end_test_and_stop_clock" . #<marker at 4965 in global_sim.vhd>)))
 ("global_sim"
  ("*package_body*" . #<marker at 5063 in global_sim.vhd>)
  ("Procedures"
   ("end_test_and_stop_clock" . #<marker at 5109 in global_sim.vhd>)
   ("read_control_reg" . #<marker at 5354 in global_sim.vhd>)
   ("read_status_reg" . #<marker at 5625 in global_sim.vhd>)
   ("read_version_reg" . #<marker at 5893 in global_sim.vhd>)
   ("read_counters" . #<marker at 6164 in global_sim.vhd>)
   ("read_master_lite_rd_data_reg" . #<marker at 6642 in global_sim.vhd>)
   ("write_control_reg" . #<marker at 6972 in global_sim.vhd>)
   ("write_converter_setup_reg" . #<marker at 7342 in global_sim.vhd>)
   ("write_mm2s_size_reg" . #<marker at 7735 in global_sim.vhd>)
   ("write_master_lite_wr_setup_reg" . #<marker at 8110 in global_sim.vhd>)
   ("write_master_lite_wr_add_reg" . #<marker at 8518 in global_sim.vhd>)
   ("write_master_lite_wr_data_reg" . #<marker at 8921 in global_sim.vhd>)
   ("write_master_lite_rd_setup_reg" . #<marker at 9326 in global_sim.vhd>)
   ("write_master_lite_rd_add_reg" . #<marker at 9734 in global_sim.vhd>)
   ("write_control_reg_system_enable" . #<marker at 10170 in global_sim.vhd>)
   ("write_control_reg_system_stop" . #<marker at 10498 in global_sim.vhd>)
   ("write_control_reg_soft_reset" . #<marker at 10822 in global_sim.vhd>)
   ("write_master_lite_write_request" . #<marker at 11144 in global_sim.vhd>)
   ("write_master_lite_read_request" . #<marker at 11730 in global_sim.vhd>))))
