(("axi_if_converter (ent)" . #<marker at 1057 in hierarchy.vhd>)
 ("RTL (arch)..."
  ("*architecture declaration*" . #<marker at 10723 in hierarchy.vhd>)
  ("axi_lite_regs (cmp)" . #<marker at 15177 in hierarchy.vhd>)
  ("input_buffer (cmp)" . #<marker at 17684 in hierarchy.vhd>)
  ("core_converter (cmp)" . #<marker at 20906 in hierarchy.vhd>)
  ("core_converter (cmp)" . #<marker at 25059 in hierarchy.vhd>)
  ("axi_lite_master (cmp)" . #<marker at 29213 in hierarchy.vhd>)
  ("clk_div (cmp)" . #<marker at 31113 in hierarchy.vhd>)
  ("clk_sync (cmp)" . #<marker at 31411 in hierarchy.vhd>)
  ("pattern_counter (cmp)" . #<marker at 31664 in hierarchy.vhd>)
  ("pattern_counter (cmp)" . #<marker at 32245 in hierarchy.vhd>)
  ("core_fsm (cmp)" . #<marker at 32826 in hierarchy.vhd>)
  ("core_fsm (cmp)" . #<marker at 33650 in hierarchy.vhd>))
 ("pattern_counter (ent)" . #<marker at 34613 in hierarchy.vhd>)
 ("RTL (arch)..."
  ("*architecture declaration*" . #<marker at 35214 in hierarchy.vhd>)
  ("pattern_count_proc (proc)" . #<marker at 35438 in hierarchy.vhd>))
 ("clk_div (ent)" . #<marker at 36169 in hierarchy.vhd>)
 ("RTL (arch)..."
  ("*architecture declaration*" . #<marker at 36433 in hierarchy.vhd>)
  ("div_proc (proc)" . #<marker at 36552 in hierarchy.vhd>)
  ("BUFG (cmp)" . #<marker at 36995 in hierarchy.vhd>))
 ("clk_sync (ent)" . #<marker at 37205 in hierarchy.vhd>)
 ("RTL (arch)..."
  ("*architecture declaration*" . #<marker at 37446 in hierarchy.vhd>)
  ("clk_fs_sync_proc (proc)" . #<marker at 37525 in hierarchy.vhd>))
 ("input_buffer (ent)" . #<marker at 38138 in hierarchy.vhd>)
 ("RTL (arch)..."
  ("*architecture declaration*" . #<marker at 40351 in hierarchy.vhd>)
  ("bram_logic (pcd)" . #<marker at 40969 in hierarchy.vhd>)
  ("bram_logic_rst (pcd)" . #<marker at 41675 in hierarchy.vhd>)
  ("read_to_output_reg_logic (pcd)" . #<marker at 42053 in hierarchy.vhd>)
  ("read_to_output_reg_logic_rst (pcd)" . #<marker at 43499 in hierarchy.vhd>)
  ("bram_pointer_position_calc (pcd)" . #<marker at 44216 in hierarchy.vhd>)
  ("bram_pointer_position_rst (pcd)" . #<marker at 44699 in hierarchy.vhd>)
  ("load_output_reg (pcd)" . #<marker at 45008 in hierarchy.vhd>)
  ("load_output_reg_rst (pcd)" . #<marker at 46117 in hierarchy.vhd>)
  ("blk_mem_gen_0 (cmp)" . #<marker at 48671 in hierarchy.vhd>)
  ("blk_mem_gen_0 (cmp)" . #<marker at 49129 in hierarchy.vhd>)
  ("axi_bram_logic_l (proc)" . #<marker at 50816 in hierarchy.vhd>)
  ("axi_bram_logic_r (proc)" . #<marker at 51702 in hierarchy.vhd>)
  ("read_to_output_reg_l (proc)" . #<marker at 52588 in hierarchy.vhd>)
  ("read_to_output_reg_r (proc)" . #<marker at 53998 in hierarchy.vhd>)
  ("bram_ptr_pos_l_proc (proc)" . #<marker at 55408 in hierarchy.vhd>)
  ("bram_ptr_pos_r_proc (proc)" . #<marker at 56130 in hierarchy.vhd>)
  ("output_reg_loading_l (proc)" . #<marker at 56853 in hierarchy.vhd>)
  ("output_reg_loading_r (proc)" . #<marker at 58072 in hierarchy.vhd>)
  ("delay_output_reg_valid_l (proc)" . #<marker at 59290 in hierarchy.vhd>)
  ("delay_output_reg_valid_r (proc)" . #<marker at 59691 in hierarchy.vhd>))
 ("core_fsm (ent)" . #<marker at 60224 in hierarchy.vhd>)
 ("RTL (arch)..."
  ("*architecture declaration*" . #<marker at 61028 in hierarchy.vhd>)
  ("fsm_axi_full (proc)" . #<marker at 61560 in hierarchy.vhd>))
 ("core_converter (ent)" . #<marker at 64758 in hierarchy.vhd>)
 ("RTL (arch)..."
  ("*architecture declaration*" . #<marker at 69266 in hierarchy.vhd>)
  ("clogb2 (fun)" . #<marker at 69309 in hierarchy.vhd>)
  ("fsm_proc (proc)" . #<marker at 76576 in hierarchy.vhd>)
  ("read_burst_size_calc_proc (proc)" . #<marker at 82084 in hierarchy.vhd>)
  ("araddr_proc (proc)" . #<marker at 83926 in hierarchy.vhd>)
  ("arvalid_proc (proc)" . #<marker at 84531 in hierarchy.vhd>)
  ("arlen_proc (proc)" . #<marker at 85478 in hierarchy.vhd>)
  ("rdata_counter_proc (proc)" . #<marker at 85835 in hierarchy.vhd>)
  ("rdata_total_counter_proc (proc)" . #<marker at 86311 in hierarchy.vhd>)
  ("r_done_proc (proc)" . #<marker at 86955 in hierarchy.vhd>)
  ("write_burst_size_calc_proc (proc)" . #<marker at 87409 in hierarchy.vhd>)
  ("awaddr_proc (proc)" . #<marker at 89364 in hierarchy.vhd>)
  ("strobe_burst_proc (proc)" . #<marker at 89968 in hierarchy.vhd>)
  ("awlen_proc (proc)" . #<marker at 91134 in hierarchy.vhd>)
  ("awvalid_proc (proc)" . #<marker at 91491 in hierarchy.vhd>)
  ("wdata_counter_proc (proc)" . #<marker at 92441 in hierarchy.vhd>)
  ("wdata_total_counter_proc (proc)" . #<marker at 92964 in hierarchy.vhd>)
  ("wlast_proc (proc)" . #<marker at 94162 in hierarchy.vhd>)
  ("bready_proc (proc)" . #<marker at 95408 in hierarchy.vhd>)
  ("request_edge_detection_proc (proc)" . #<marker at 96265 in hierarchy.vhd>)
  ("pattern_cnt_proc (proc)" . #<marker at 96676 in hierarchy.vhd>))
 ("axi_lite_regs (ent)" . #<marker at 98535 in hierarchy.vhd>)
 ("RTL (arch)..."
  ("*architecture declaration*" . #<marker at 101110 in hierarchy.vhd>)
  ("add_bit (pcd)" . #<marker at 105604 in hierarchy.vhd>)
  ("axi_awready_proc (proc)" . #<marker at 106465 in hierarchy.vhd>)
  ("axi_awaddr_proc (proc)" . #<marker at 107109 in hierarchy.vhd>)
  ("axi_wready_proc (proc)" . #<marker at 107732 in hierarchy.vhd>)
  ("axi_bvalid_proc (proc)" . #<marker at 108531 in hierarchy.vhd>)
  ("axi_arready_proc (proc)" . #<marker at 109530 in hierarchy.vhd>)
  ("axi_rvalid_proc (proc)" . #<marker at 110619 in hierarchy.vhd>)
  ("axi_rdata_proc (proc)" . #<marker at 111278 in hierarchy.vhd>)
  ("address_decoding_proc (proc)" . #<marker at 111717 in hierarchy.vhd>)
  ("read_write_regs_proc (proc)" . #<marker at 113845 in hierarchy.vhd>)
  ("read_only_regs_proc (proc)" . #<marker at 118982 in hierarchy.vhd>)
  ("control_reg_signals_proc (proc)..."
   ("*proc*" . #<marker at 120721 in hierarchy.vhd>)
   ("add_out_sigH (pcd)" . #<marker at 120780 in hierarchy.vhd>))
  ("soft_reset_out_proc (proc)" . #<marker at 121332 in hierarchy.vhd>)
  ("mm2s_proc (proc)" . #<marker at 122005 in hierarchy.vhd>)
  ("master_lite_proc (proc)" . #<marker at 122656 in hierarchy.vhd>))
 ("axi_lite_master (ent)" . #<marker at 123512 in hierarchy.vhd>)
 ("RTL (arch)..."
  ("*architecture declaration*" . #<marker at 125536 in hierarchy.vhd>)
  ("awvalid_proc (proc)" . #<marker at 127058 in hierarchy.vhd>)
  ("wvalid_proc (proc)" . #<marker at 127554 in hierarchy.vhd>)
  ("awaddr_proc (proc)" . #<marker at 128043 in hierarchy.vhd>)
  ("wdata_proc (proc)" . #<marker at 128400 in hierarchy.vhd>)
  ("bready_proc (proc)" . #<marker at 128915 in hierarchy.vhd>)
  ("arvalid_proc (proc)" . #<marker at 129401 in hierarchy.vhd>)
  ("rready_proc (proc)" . #<marker at 129901 in hierarchy.vhd>)
  ("araddr_proc (proc)" . #<marker at 130387 in hierarchy.vhd>)
  ("do_read (proc)" . #<marker at 130742 in hierarchy.vhd>)
  ("error_proc (proc)" . #<marker at 131534 in hierarchy.vhd>)))
